// Toast
export const MAKE_TOAST = 'MAKE_TOAST'

// Category
//    Actions
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST'
export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const UPDATE_CATEGORY_STATUS = 'UPDATE_CATEGORY_STATUS'
//    Mutations
export const UPDATE_CATEGORY_LIST = 'UPDATE_CATEGORY_LIST'
export const UPDATE_CATEGORY_FILTERED_LIST = 'UPDATE_CATEGORY_FILTERED_LIST'
export const SET_CATEGORY_LOADING = 'SET_CATEGORY_LOADING'
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY'
export const SHOW_UPDATE_CATEGORY_MODAL = 'SHOW_UPDATE_CATEGORY_MODAL'
export const UPDATE_CATEGORY_STATE = 'UPDATE_CATEGORY_STATE'
export const UPDATE_DELETE_CATEGORY_MODAL_STATE = 'UPDATE_DELETE_CATEGORY_MODAL_STATE'
export const DISABLED_DELETE_BUTTON = 'DISABLED_DELETE_BUTTON'
export const SELECT_CATEGORY = 'SELECT_CATEGORY'

// Application User
//    Actions
export const GET_APPLICATION_USER = 'GET_APPLICATION_USER'
//    Mutations
export const UPDATE_APPLICATION_USER = 'UPDATE_APPLICATION_USER'
export const UPDATE_APPLICATION_USER_LOADING = 'UPDATE_APPLICATION_USER_LOADING'
